name: ubuntu24.04-dev

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # 每周日UTC时间00:00执行
  push:
    tags:
      - "*" # 当推送任何标签时触发
jobs:
  scripts-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACTIONS }}

      - name: preprocessing
        run: |
          sudo apt-get install -y dos2unix
          find -type f -name *.sh | xargs dos2unix
          find -type f -name *.sh | xargs chmod +x

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1071
        with:
          severity: error

  build-core-image:
    strategy:
      matrix:
        include:
          - distro: "ubuntu24.04"
            arch: "amd64"
            runner: "ubuntu-24.04"
          - distro: "ubuntu24.04"
            arch: "arm64"
            runner: "ubuntu-24.04-arm"
    runs-on: ${{ matrix.runner }}
    needs: [scripts-verify]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACTIONS }}

      - name: Grant execution permissions
        run: |
          sudo apt-get install -y dos2unix
          find -type f -name *.sh | xargs dos2unix
          find -type f -name *.sh | xargs chmod +x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to official hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/os/ubuntu
          file: dockerfiles/os/ubuntu/24.04/core.dockerfile
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: |
            sqjian/venv:${{ matrix.distro }}-${{ matrix.arch }}
          provenance: false

      - name: Create and push multi-arch manifest for Docker Hub
        run: |
          docker manifest create --amend sqjian/venv:ubuntu24.04 \
            sqjian/venv:ubuntu24.04-amd64 \
            sqjian/venv:ubuntu24.04-arm64
          docker manifest push sqjian/venv:ubuntu24.04

  build-extra-image:
    strategy:
      matrix:
        include:
          - distro: "ubuntu24.04-extra"
            arch: "amd64"
            runner: "ubuntu-24.04"
          - distro: "ubuntu24.04-extra"
            arch: "arm64"
            runner: "ubuntu-24.04-arm"
    runs-on: ${{ matrix.runner }}
    needs: [scripts-verify]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACTIONS }}

      - name: Grant execution permissions
        run: |
          sudo apt-get install -y dos2unix
          find -type f -name *.sh | xargs dos2unix
          find -type f -name *.sh | xargs chmod +x

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to official hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/os/ubuntu
          file: dockerfiles/os/ubuntu/24.04/extra.dockerfile
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: |
            sqjian/venv:${{ matrix.distro }}-${{ matrix.arch }}
          provenance: false

      - name: Create and push multi-arch manifest for Docker Hub
        run: |
          docker manifest create --amend sqjian/venv:ubuntu24.04-extra \
            sqjian/venv:ubuntu24.04-extra-amd64 \
            sqjian/venv:ubuntu24.04-extra-arm64
          docker manifest push sqjian/venv:ubuntu24.04-extra
